main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('map/', views.map, name='map'),
  path('workouts_index/', views.workouts_index, name='workouts_index'),
  path('exercises/', views.exercises_index, name='exercises_index'),
  path('exercises/create/', views.ExerciseCreate.as_view(), name='exercises_form'),
  path('exercises/<int:exercise_id>/detail', views.exercises_detail, name='detail'),
  path('exercises/<str:muscle>/', views.muscle_index, name='muscle_exercise_index'),
  path('exercises/<str:muscle>/<int:exercise_id>/', views.muscle_exercise_detail, name='muscle_exercise_detail'),
  path('exercises/<int:pk>/update/', views.ExerciseUpdate.as_view(), name='exercises_update'),
  path('exercises/<int:pk>/delete/', views.ExerciseDelete.as_view(), name='exercises_delete'),
  path('user_exercises/', views.user_exercises, name='user_exercises'),
  path('accounts/signup/', views.signup, name='signup'),
  path('profile/', views.profile, name='profile'),
  path('<int:pk>/update/', views.ProfileUpdate.as_view(), name='profiles_update'),
  path('<int:pk>/delete/', views.ProfileDelete.as_view(), name='profiles_delete'),
  path('workout/create/', views.create_workout, name='workout_create'),
  path('workouts/<int:pk>/begin/', views.begin_workout, name='begin_workout'),
  path('workouts/<int:pk>/update/', views.update_workout, name='workout_update'),
  path('workouts/<int:pk>/delete/', views.WorkoutDelete.as_view(), name='workout_delete'),
  path('workouts/<int:pk>/', views.workouts_detail, name='workouts_detail'),
  path('workouts/', views.workouts_index, name='workouts_index'),
  path('workouts/history', views.workouts_history, name='workouts_history'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date
from django.db.models.signals import post_save
from django.dispatch import receiver

WEIGHT = (
    ('kg', 'Kilograms'),
    ('lbs', 'Pounds'),
)

HEIGHT = (
    ('cm', 'Centimeters'),
    ('ft', 'Feet'),
)

DIFFICULTY = (
    ('b', 'Beginner'),
    ('i', 'Intermediate'),
    ('e', 'Expert'),
)

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    age = models.IntegerField(blank=True, null=True)
    
    height = models.IntegerField(blank=True, null=True)
    height_unit = models.CharField(
        max_length=100,
        blank=True,
        choices=HEIGHT,
        default=HEIGHT[0][0]
    )
    weight = models.IntegerField(blank=True, null=True)
    weight_unit = models.CharField(
        max_length=100,
        blank=True,
        choices=WEIGHT,
        default=WEIGHT[0][0]
    )

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('profile')
    
    def delete(self, *args, **kwargs):
        self.user.delete()
        super(Profile, self).delete(*args, **kwargs)

    # def convert_weight(self, target_unit):
    #     if self.weight_unit == target_unit:
    #         return self.weight

    #     if self.weight_unit == WeightUnitChoices.KG and target_unit == WeightUnitChoices.LBS:
    #         return self.weight * 2.20462
    #     elif self.weight_unit == WeightUnitChoices.LBS and target_unit == WeightUnitChoices.KG:
    #         return self.weight * 0.453592
    #     else:
    #         return self.weight

    # def convert_height(self, target_unit):
    #     if self.height_unit == target_unit:
    #         return self.height

    #     if self.height_unit == HeightUnitChoices.CM and target_unit == HeightUnitChoices.FT:
    #         feet = int(self.height / 30.48)
    #         inches = round((self.height % 30.48) / 2.54)
    #         return f"{feet} ft {inches} in"
    #     elif self.height_unit == HeightUnitChoices.FT and target_unit == HeightUnitChoices.CM:
    #         total_inches = self.height * 12
    #         return round(total_inches * 2.54)
    #     else:
    #         return self.height
        
@receiver(post_save, sender=User)
def create_or_update_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    else:
        instance.profile.save()
  
class ImportedExercise(models.Model):
    name = models.CharField(max_length=100, default='')
    force = models.CharField(max_length=100, default='', null=True, blank=True)
    level = models.CharField(
    max_length=20,
    choices=DIFFICULTY,
    default=DIFFICULTY[0][0],
    )
    mechanic = models.CharField(max_length=100, default='', null=True, blank=True)
    equipment = models.CharField(max_length=100, default='', null=True, blank=True)
    primaryMuscles = models.CharField(max_length=100, default='')
    secondaryMuscles = models.CharField(max_length=100, default='', null=True, blank=True)
    category = models.CharField(max_length=100, default='', null=True, blank=True)
    images = models.CharField(max_length=100, default='', null=True, blank=True)
    instructions = models.CharField(max_length=1000, default='')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    photo = models.ImageField(upload_to='imported_exercise_photos/', blank=True, null=True)
    imported = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} ({self.id})'
    def get_absolute_url(self):
        return reverse('detail', args=[str(self.id)])

class Workout(models.Model):
  name = models.CharField(max_length=100)
  exercises = models.ManyToManyField('ImportedExercise', through='ExerciseInWorkout')
  is_template = models.BooleanField(default=True)
  date = models.DateField(null=True, blank=True)
  user = models.ForeignKey(User, on_delete=models.CASCADE, default='1') 

  def __str__(self):
    return f'{self.name} ({self.id})'
  
  def get_absolute_url(self):
    return reverse('workouts_detail', kwargs={'pk': self.id})
  
  

class ExerciseInWorkout(models.Model):
    workout = models.ForeignKey(Workout, on_delete=models.CASCADE)
    exercise = models.ForeignKey(ImportedExercise, on_delete=models.CASCADE)
    sets = models.IntegerField(null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)
    reps = models.IntegerField(null=True, blank=True)
    tempo = models.CharField(max_length=10, null=True, blank=True)
    rest = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return f"{self.exercise} in {self.workout}"

main_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import ImportedExercise, Profile, Workout, DIFFICULTY

class ExerciseForm(forms.ModelForm):
    level = forms.ChoiceField(
        choices=DIFFICULTY,
        widget=forms.Select(attrs={'class':'browser-default'}),
    )
    primaryMuscles = forms.ChoiceField(
        choices=[(muscle, muscle) for muscle in set(ImportedExercise.objects.values_list('primaryMuscles', flat=True).distinct())],
        widget=forms.Select(attrs={'class':'browser-default'}),
    )

    class Meta:
        model = ImportedExercise
        fields = ['name', 'level', 'primaryMuscles', 'instructions', 'photo']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'age', 'height', 'height_unit', 'weight', 'weight_unit']

class WorkoutForm(ModelForm):
    class Meta:
        model = Workout
        fields = ['name', 'date', 'exercises', 'is_template']

main_app/views.py
import uuid
import boto3
from django.http import HttpResponseBadRequest
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseForbidden
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Q
from .models import Profile, Workout, ExerciseInWorkout, ImportedExercise, DIFFICULTY
from .forms import ExerciseForm, ProfileForm, WorkoutForm
from collections import defaultdict
from datetime import date
import requests
import json

# API-key = gXLCkA3vzl+aRqbGHmQJUg==isLFzMJoImFUhgL5
# Create your views here.
def get_difficulty_label(key):
    for k, label in DIFFICULTY:
        if k == key:
            return label
    return ''


def home(request):
  if request.method == 'GET':
    api_url = 'https://api.api-ninjas.com/v1/quotes?category=dad'
    api_request = requests.get(api_url, headers={'X-Api-Key': 'gXLCkA3vzl+aRqbGHmQJUg==isLFzMJoImFUhgL5'})
    try:
      api_data = json.loads(api_request.content)
      if api_data and isinstance(api_data, list) and len(api_data) > 0:
        quote_info = api_data[0]
        quote = quote_info['quote']
        author = quote_info['author']
      else:
        quote = "No quotes available in the given category."
        author = "Unknown"

    except Exception as e:
      quote = "Oops, There was an error"
      author = "Unknown"
      print(e)

  return render(request, 'home.html', {'quote': quote, 'author': author})


def about(request):
  return render(request, 'about.html')

def map(request):
  return render(request, 'map.html')


@login_required
def exercises_index(request):
    all_exercises = ImportedExercise.objects.filter(Q(user=request.user) | Q(imported=True))

    categorized_exercises_dict = defaultdict(list)
    
    for exercise in all_exercises:
        primary_muscles = exercise.primaryMuscles
        categorized_exercises_dict[primary_muscles].append(exercise)

    categorized_exercises_dict = dict(categorized_exercises_dict)

    return render(request, 'exercises/exercises_index.html', {
        'combined_exercises_dict': categorized_exercises_dict,
    })

@login_required
def muscle_index(request, muscle):
    exercises = ImportedExercise.objects.filter(
        Q(primaryMuscles__contains=muscle) & 
        (Q(imported=True) | Q(user=request.user))
    )
    
    for exercise in exercises:
        if isinstance(exercise.images, str) and exercise.images:
            try:
                exercise.images = eval(exercise.images)
            except Exception as e:
                print(f"Failed to evaluate images for exercise {exercise.id}: {e}")
                exercise.images = []
        else:
            exercise.images = []
        
        exercise.name = exercise.name.replace('/', '-')
    
    context = {
        'muscle_name': muscle,
        'exercises': exercises,
    }
    return render(request, 'exercises/muscle_index.html', context)



def muscle_exercise_detail(request, muscle, exercise_id):
    exercise = ImportedExercise.objects.get(id=exercise_id)

    if isinstance(exercise.instructions, str) and exercise.instructions:
        try:
            exercise.instructions = eval(exercise.instructions)
        except SyntaxError:
            exercise.instructions = [exercise.instructions]
    else:
        exercise.instructions = []

    steps_list = []
    for instruction in exercise.instructions:
        steps = instruction.split('. ')
        steps_list.extend(steps)

    if isinstance(exercise.images, str) and exercise.images:
        try:
            exercise.images = eval(exercise.images)
        except Exception as e:
            print(f"Failed to evaluate images for exercise {exercise.id}: {e}")
            exercise.images = []
    else:
        exercise.images = []
        
    exercise_level_label = get_difficulty_label(exercise.level)

    context = {
        'muscle_name': muscle,
        'exercise': exercise,
        'steps_list': steps_list,
        'exercise_level_label': exercise_level_label,
    }
    return render(request, 'exercises/muscle_exercise_detail.html', context)



@login_required
def profile(request):
  profile = Profile.objects.get(user=request.user)

  height_display = profile.height
  # if profile.height_unit == 'ft':
  #   height_display = profile.convert_height('ft')
  weight_display = profile.weight
  # if profile.weight_unit == 'lbs':
  #   weight_display = profile.convert_weight('lbs')

  context = {
    'profile': profile,
    'height_display': height_display,
    'weight_display': weight_display
  }
  return render(request, 'profile.html', context)

@login_required
def user_exercises(request):
    user_exercises = ImportedExercise.objects.filter(user=request.user)

    for exercise in user_exercises:
        formatted_primary_muscles = [
            muscle.strip("[]'").capitalize() for muscle in exercise.primaryMuscles.split(',')
        ]
        exercise.primaryMuscles = ", ".join(formatted_primary_muscles)

        exercise.level = get_difficulty_label(exercise.level) 

    return render(request, 'exercises/user_exercises.html', {'user_exercises': user_exercises})

@login_required
def exercises_detail(request, exercise_id):
    exercise = get_object_or_404(ImportedExercise, id=exercise_id)


    formatted_primary_muscles = [
        muscle.strip("[]'").capitalize() for muscle in exercise.primaryMuscles.split(',')
    ]
    exercise.primaryMuscles = ", ".join(formatted_primary_muscles)

    exercise_level_label = get_difficulty_label(exercise.level)

    steps_list = []
    for instruction in exercise.instructions:
        steps = instruction.split('. ')
        steps_list.extend(steps)

    context = {
        'exercise': exercise,
        'exercise_level_label': exercise_level_label,
        'steps_list': steps_list,
    }
    return render(request, 'exercises/detail.html', context)


class ExerciseCreate(CreateView):
    model = ImportedExercise
    form_class = ExerciseForm
    template_name = 'main_app/exercises_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.imported = False

        photo_file = self.request.FILES.get('photo')
        if photo_file:
            unique_filename = f"{uuid.uuid4().hex}.jpg"

            s3_client = boto3.client('s3')
            s3_client.upload_fileobj(photo_file, 'fitbuddy-bucket', unique_filename)
            form.instance.photo = unique_filename
        else:
            form.instance.photo = None

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('detail', kwargs={'exercise_id': self.object.pk})
    
def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('home')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

class ProfileUpdate(UpdateView):
    model = Profile
    # form_class = ProfileForm
    fields = ['bio', 'age', 'height', 'height_unit', 'weight', 'weight_unit']
    # template_name = 'main_app/profile_form.html'
    # context_object_name = 'profile'
    success_url = reverse_lazy('profile')

    def form_valid(self, form):
        profile = form.save(commit=False)

        # if 'height_unit' in form.changed_data:
        #     profile.height = profile.convert_height(profile.height_unit)
        # if 'weight_unit' in form.changed_data:
        #     profile.weight = profile.convert_weight(profile.weight_unit)

        profile.save()
        return super().form_valid(form)

class ProfileDelete(DeleteView):
    model = Profile
    success_url = '/'


class WorkoutDelete(DeleteView):
    model = Workout
    success_url = '/workouts/'

@login_required
def workouts_index (request):
    workouts = Workout.objects.filter(user=request.user, is_template=True)
    return render(request, 'workouts/index.html', {
        'workouts': workouts
    })


def workouts_detail(request, pk):
    workout = Workout.objects.get(id=pk)
    exercise_in_workouts = ExerciseInWorkout.objects.filter(workout=workout)
    return render(request, 'workouts/detail.html', {
        'workout': workout,
        'exercise_in_workouts': exercise_in_workouts,
    })

def create_workout(request):
    if request.method == 'POST':
        form = WorkoutForm(request.POST)
        if form.is_valid():
            workout = form.save(commit=False)
            workout.is_template = True

            exercise_ids = request.POST.get('exercises').split(',')
            all_exercises_valid = True
            exercises_in_workout = []
            for exercise_id in exercise_ids:
              exercise_id = exercise_id.strip() 
              if exercise_id:
                exercise = ImportedExercise.objects.get(pk=int(exercise_id))
                exercise_in_workout = ExerciseInWorkout(workout=workout, exercise=exercise)
 
                sets = request.POST.get(f'sets_{exercise_id}')
                if sets and (not sets.isdigit() or int(sets) < 0):
                    all_exercises_valid = False
                    form.add_error(None, f'Invalid sets for exercise {exercise.name}')
                elif sets:
                    exercise_in_workout.sets = sets
                
                weight = request.POST.get(f'weight_{exercise_id}')
                if weight and (not weight.isdigit() or int(weight) < 0):
                    all_exercises_valid = False

main_app/templates/workouts/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
  <div class="col s12 m6">
    <div class="card">
      <div class="card-content">
        <h3 style="text-align: center;">{{ workout.name|capfirst }}</h3>
        <ul class="collection" id="workout-exercises">
          {% for exercise_in_workout in exercise_in_workouts %}
            <li class="collection-item avatar">
              <i class="material-icons circle green">fitness_center</i>
              <h6>{{ exercise_in_workout.exercise.name|capfirst }}</h6>
              <p>
                <strong>Sets:</strong> {{ exercise_in_workout.sets }}<br>
                <strong>Weight:</strong> {{ exercise_in_workout.weight }}<br>
                <strong>Reps:</strong> {{ exercise_in_workout.reps }}<br>
                <strong>Tempo:</strong> {{ exercise_in_workout.tempo }}<br>
                <strong>Rest:</strong> {{ exercise_in_workout.rest }}
              </p>
            </li>
          {% endfor %}
        </ul>
      </div>
      <div class="card-action">
        <a href="{% url 'begin_workout' workout.id %}" class="waves-effect waves-light btn-small">Begin Workout</a>
        <a href="{% url 'workout_update' workout.id %}" class="waves-effect waves-light btn-small blue">Edit</a>
        <a href="{% url 'workout_delete' workout.id %}" class="waves-effect waves-light btn-small red">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

main_app/templates/workouts/history.html
{% extends 'base.html' %} 
{% block content %}

<h3 style="text-align: center;">Workout History</h3>

<div class="row">
{% for workout in workouts %}
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <a href="{% url 'workouts_detail' workout.id %}">
          <h6 style="text-align: center;">{{ workout.name|capfirst }}</h6>
          <p style="text-align: center;">{{ workout.date }}</p>
        </a>
      </div>
      <div class="card-action">
        <a href="{% url 'workout_delete' workout.id %}" class="waves-effect waves-light btn-small red">Delete</a>
      </div>
    </div>
  </div>
{% endfor %}
</div>

{% endblock %}

main_app/templates/workouts/index.html
{% extends 'base.html' %} 
{% block content %}

<h3 style="text-align: center;">Your Workout Templates</h3>

<div class="row">
{% for workout in workouts %}
  <div class="col s12 m6">
    <div class="card">
      <div class="card-content">
        <a href="{% url 'workouts_detail' workout.id %}">
          <h6 style="text-align: center;">{{ workout.name|capfirst }}</h6>
        </a>
      </div>
      <div class="card-action">
        <a href="{% url 'begin_workout' workout.id %}" class="waves-effect waves-light btn-small">Begin Workout</a>
        <a href="{% url 'workout_update' workout.id %}" class="waves-effect waves-light btn-small blue">Edit</a>
        <a href="{% url 'workout_delete' workout.id %}" class="waves-effect waves-light btn-small red">Delete</a>
      </div>
    </div>
  </div>
{% endfor %}
</div>

{% endblock %}

main_app/templates/workouts/workout_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  {% if form.instance.pk %}
    <h1>Edit {{ workout_name }}</h1>
  {% else %}
    <h1>Create a New Workout</h1>
  {% endif %}

  {% if form.instance.pk %}
    <form action="{% url 'workout_update' form.instance.pk %}" method="POST">
  {% else %}
    <form action="{% url 'workout_create' %}" method="POST">
  {% endif %}
    {% csrf_token %}

    <div class="input-field">
      <label for="id_name">Workout Name:</label>
      <input type="text" id="id_name" name="name" value="{{ form.instance.name }}" required />
    </div>

    <ul id="workout-exercises">
      {% if form.instance.pk %}
            {% for exercise_in_workout in form.instance.exerciseinworkout_set.all %}
        <li data-exercise-id="{{ exercise_in_workout.exercise.id }}">
          <span>{{ exercise_in_workout.exercise.name }}</span>
          <span> Sets: {{ exercise_in_workout.sets }} </span>
          <span> Weight: {{ exercise_in_workout.weight }} </span>
          <span> Reps: {{ exercise_in_workout.reps }} </span>
          <span> Tempo: {{ exercise_in_workout.tempo }} </span>
          <span> Rest: {{ exercise_in_workout.rest }} </span>
          <button type="button" class="delete-exercise-btn btn">Delete</button>
        </li>
      {% endfor %}
      {% endif %}
    </ul>

<input type="hidden" id="exercises-input" name="exercises" value="{% if form.instance.pk %}{% for exercise_in_workout in form.instance.exerciseinworkout_set.all %}{{ exercise_in_workout.exercise.id }} {% endfor %}{% endif %}">


    <div class="row">
        <div class="input-field col s12">
          <input type="text" id="autocomplete-input" class="autocomplete" placeholder="Start typing exercise name..." />
          <label for="autocomplete-input">Exercise</label>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s2">
          <input type="number" id="sets-input" placeholder="Sets..." />
          <label for="sets-input">Sets</label>
        </div>

        <div class="input-field col s2">
          <input type="number" id="weight-input" placeholder="Weight..." />
          <label for="weight-input">Weight</label>
        </div>

        <div class="input-field col s2">
          <input type="number" id="reps-input" placeholder="Reps..." />
          <label for="reps-input">Reps</label>
        </div>

        <div class="input-field col s2">
          <input type="text" id="tempo-input" placeholder="Tempo..." />
          <label for="tempo-input">Tempo</label>
        </div>

        <div class="input-field col s2">
          <input type="number" id="rest-input" placeholder="Rest time..." />
          <label for="rest-input">Rest Time</label>
        </div>
    </div>

    <button type="button" id="add-exercise-btn" class="btn">Add Exercise</button>
    <input type="submit" value="Submit" class="btn" />
  </form>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    document.getElementById('add-exercise-btn').addEventListener('click', addExerciseToWorkout);
    const deleteExerciseButtons = document.querySelectorAll('.delete-exercise-btn');
    deleteExerciseButtons.forEach(button => button.addEventListener('click', deleteExercise));
    const exerciseData = {
      {% for exercise in exercise_list %}
      "{{ exercise.name }}": "{{ exercise.id }}",
      {% endfor %}
    };

    console.log('exerciseData:', exerciseData);

    var elems = document.querySelectorAll('.autocomplete');
    var instances = M.Autocomplete.init(elems, {
      data: exerciseData,
      minLength: 1,
    });

    const workoutExercisesList = document.getElementById('workout-exercises');
    const exercisesInput = document.getElementById('exercises-input');

  function deleteExercise(e) {
    const listItem = e.target.closest('li');
    const exerciseId = listItem.getAttribute('data-exercise-id');

    workoutExercisesList.removeChild(listItem);

    const currentExercises = new Set(exercisesInput.value.split(',').filter(Boolean));
    currentExercises.delete(exerciseId);

    exercisesInput.value = [...currentExercises].filter(id => !!id).join(',');
  }

function addExerciseToWorkout() {
  const autocompleteInput = document.getElementById('autocomplete-input');
  const setsInput = document.getElementById('sets-input');
  const weightInput = document.getElementById('weight-input');
  const repsInput = document.getElementById('reps-input');
  const tempoInput = document.getElementById('tempo-input');
  const restInput = document.getElementById('rest-input');

  const exerciseName = autocompleteInput.value.trim();
  const sets = setsInput.value.trim();
  const weight = weightInput.value.trim();
  const reps = repsInput.value.trim();
  const tempo = tempoInput.value.trim();
  const rest = restInput.value.trim();

  if (exerciseName !== '' && exerciseData.hasOwnProperty(exerciseName)) {
    const exerciseId = exerciseData[exerciseName];

    const listItem = document.createElement('li');

    const exerciseAttributeElement = document.createElement('span');
    exerciseAttributeElement.setAttribute('data-attribute', 'exercise');
    exerciseAttributeElement.textContent = exerciseName;
    listItem.appendChild(exerciseAttributeElement);

    const setsElement = document.createElement('span');
    setsElement.setAttribute('data-attribute', 'sets');
    setsElement.textContent = 'Sets: ' + sets;
    listItem.appendChild(setsElement);

    const weightElement = document.createElement('span');
    weightElement.setAttribute('data-attribute', 'weight');
    weightElement.textContent = 'Weight: ' + weight;
    listItem.appendChild(weightElement);

    const repsElement = document.createElement('span');
    repsElement.setAttribute('data-attribute', 'reps');
    repsElement.textContent = 'Reps: ' + reps;
    listItem.appendChild(repsElement);

    const tempoElement = document.createElement('span');
    tempoElement.setAttribute('data-attribute', 'tempo');
    tempoElement.textContent = 'Tempo: ' + tempo;
    listItem.appendChild(tempoElement);

    const restElement = document.createElement('span');
    restElement.setAttribute('data-attribute', 'rest');
    restElement.textContent = 'Rest: ' + rest;
    listItem.appendChild(restElement);

    const deleteButton = document.createElement('button');
    deleteButton.type = 'button';
    deleteButton.className = 'delete-exercise-btn';
    deleteButton.textContent = 'Delete';
    deleteButton.addEventListener('click', deleteExercise);
    listItem.appendChild(deleteButton);

    workoutExercisesList.appendChild(listItem);

    const currentExercises = new Set(exercisesInput.value.split(',').filter(Boolean));

    currentExercises.add(exerciseId);

    exercisesInput.value = [...currentExercises].filter(id => !!id).join(',');

    autocompleteInput.value = ''; 
    setsInput.value = '';
    weightInput.value = '';
    repsInput.value = '';
    tempoInput.value = '';
    restInput.value = '';
  }
}
  });
</script>
{% endblock %}